---
# _module:
#   - { name: "overlay" }
#   - { name: "br_netfilter" }

# _sysctl:
#   - { key: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
#   - { key: "net.bridge.bridge-nf-call-iptables", value: 1 }
#   - { key: "net.ipv4.ip_forward", value: 1 }
#   - { key: "net.ipv6.conf.all.forwarding", value: 1 }

_repo_state_manager:
  - { state: "enable", name: "extras" }
  - { state: "enable", name: "updates" }
  - { state: "enable", name: "cr" }

# _key:
#   - { gpg: "" }

# _repo:
#   - { name: "", repo: "" }

_package:
  - { state: "latest", name: "epel-release" }
  - { state: "latest", name: "python3" }
  - { state: "latest", name: "bash" }
  - { state: "latest", name: "bash-completion" }

_service:
  - { enabled: "yes", state: "present",  name: "k3s" }

_install_script:
  - { url: "https://get.k3s.io", checksum: "", dest: "/tmp/install.sh"  }

# _pkill_script:
#   - { url: "", checksum: "", dest: ""  }

# _uninstall_script:
#   - { url: "", checksum: "", dest: ""  }

K3S_VERSION: "v1.19.3+k3s2"

server:
  token_path: /tmp/k3s_token
  url_path: /tmp/k3s_url

deployment_host:
  kube_config: /home/cclhsu/.kube/ansible_k3s_config