---
# - name: Add required modules
#   modprobe:
#     name: "{{ item.name }}"
#     state: present
#   loop:
#     "{{ _module }}"
#   tags: k3s-server

# - name: Setup required sysctl params
#   sysctl:
#     name: "{{ item.key }}"
#     value: "{{ item.value }}"
#     sysctl_set: yes
#     state: present
#     reload: yes
#   loop:
#     "{{ _sysctl }}"
#   tags: k3s-server

# - name: Add repositories
#   zypper_repository:
#     state: present
#     repo: "{{ item.repo }}"
#   loop: "{{ _repo }}"
#   changed_when: false
#   tags: k3s-server

# - name: Refresh repositories
#   zypper_repository:
#     repo: '*'
#     auto_import_keys: yes
#     runrefresh: yes
#   tags: k3s-server

# - name: Update all packages
#   zypper:
#     name: '*'
#     state: latest
#     update_cache: yes
#   changed_when: false
#   ignore_errors: true
#   tags: k3s-server

# - name: Install packages
#   zypper:
#     name: "{{ item.name }}"
#     state: "{{ item.state }}"
#     disable_gpg_check: yes
#     update_cache: yes
#     # extra_args: ''
#   loop: "{{ _package }}"
#   register: result
#   until: result is succeeded
#   tags: k3s-server

# - name: just force systemd to reread configs
#   systemd:
#     daemon_reload: yes
#   tags: k3s-server

# - name: Start and enable services
#   systemd:
#     name: "{{ item.name }}"
#     state: started
#     enabled: yes
#     daemon_reload: yes
#   loop: "{{ _service }}"
#   register: result
#   until: result is succeeded
#   tags: k3s-server

# - name: Add /usr/local/bin to sudo secure_path
#   lineinfile:
#     line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
#     regexp: "Defaults(\s)*secure_path(\s)*="
#     state: present
#     insertafter: EOF
#     path: /etc/sudoers
#     validate: 'visudo -cf %s'
#   tags: k3s-server

- name: Download script
  get_url:
    url: "{{ item.url }}"
    # checksum: "{{ item.checksum }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: k3s-server

- name: Execute script
  shell: "INSTALL_K3S_SELINUX_WARN=true INSTALL_K3S_VERSION={{ K3S_VERSION }} sh {{ item.dest }}"
  become: true
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: k3s-server

- name: Remove script
  file:
    path: "{{ item.dest }}"
    state: absent
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: k3s-server

- name: Start and enable services
  systemd:
    name: "{{ item.name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop: "{{ _service }}"
  register: result
  until: result is succeeded
  tags: k3s-server

- name: Wait until node token is generated
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
  run_once: true
  tags: k3s-server

- name: Get node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: K3S_TOKEN
  run_once: true
  tags: k3s-server

- name: Clean up node token contents
  set_fact: 
    K3S_TOKEN: "{{ K3S_TOKEN['content'] | b64decode | replace('\n', '')}}"
    cacheable: yes
  run_once: yes
  tags: k3s-server

- name: Print cluster node token
  debug:
    msg: "{{ K3S_TOKEN }}"
  tags: k3s-server

- name: Set server address
  register: K3S_URL
  set_fact:
    K3S_URL: "https://{{ ansible_host }}:6443"
    cacheable: yes
  run_once: yes
  tags: k3s-server

- name: Print server address
  debug:
    msg: "{{ K3S_URL }}"
  tags: k3s-server

- name: copy the output to a local file
  copy:
    content: "{{ K3S_TOKEN }}"
    dest: "{{ server.token_path }}"
  delegate_to: localhost
  tags: k3s-server

- name: copy the output to a local file
  copy:
    content: "{{ K3S_URL }}"
    dest: "{{ server.url_path }}"
  delegate_to: localhost
  tags: k3s-server

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="
  tags: k3s-server

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="
  tags: k3s-server

- name: Replace https://localhost:6443 by https://master-ip:6443
  replace:
    path: ~{{ ansible_user }}/.kube/config
    regexp: '127.0.0.1'
    replace: "{{ ansible_host }}"
  tags: k3s-server

- name: Fetch config file to user home directory
  fetch:
    src: ~{{ ansible_user }}/.kube/config
    dest: "{{ deployment_host.kube_config }}"
    flat: yes
  tags: k3s-server