---
_package:
  - { state: "latest", name: "python3" }
  - { state: "latest", name: "bash" }
  - { state: "latest", name: "bash-completion" }

# _service:
#   - { enabled: "yes", state: "present",  name: "" }

# _install_script:
#   - { url: "", checksum: "", dest: ""  }

_pkill_script:
  - { url: "", checksum: "", dest: "/usr/local/bin/k3s-killall.sh"  }

_uninstall_script:
  - { url: "", checksum: "", dest: "/usr/local/bin/k3s-agent-uninstall.sh"  }

deployment_host:
  kube_config: /home/cclhsu/.kube/ansible_k3s_config
