---
# _module:
#   - { name: "overlay" }
#   - { name: "br_netfilter" }

# _sysctl:
#   - { key: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
#   - { key: "net.bridge.bridge-nf-call-iptables", value: 1 }
#   - { key: "net.ipv4.ip_forward", value: 1 }
#   - { key: "net.ipv6.conf.all.forwarding", value: 1 }

# _key:
#   - { gpg: "" }

# _repo:
#   - { name: "", repo: "" }

_package:
  - { state: "latest", name: "python3" }
  - { state: "latest", name: "bash" }
  - { state: "latest", name: "bash-completion" }

_service:
  - { enabled: "yes", state: "present",  name: "k3s-agent" }

_install_script:
  - { url: "https://get.k3s.io", checksum: "", dest: "/tmp/install.sh"  }

# _pkill_script:
#   - { url: "", checksum: "", dest: ""  }

# _uninstall_script:
#   - { url: "", checksum: "", dest: ""  }

K3S_VERSION: "v1.19.3+k3s2"
K3S_TOKEN: "{{ lookup('file', '/tmp/k3s_token' ) }}"
K3S_URL: "{{ lookup('file', '/tmp/k3s_url' ) }}"