---
# - name: Add required modules
#   modprobe:
#     name: "{{ item.name }}"
#     state: present
#   loop:
#     "{{ _module }}"
#   tags: common

# - name: Setup required sysctl params
#   sysctl:
#     name: "{{ item.key }}"
#     value: "{{ item.value }}"
#     sysctl_set: yes
#     state: present
#     reload: yes
#   loop:
#     "{{ _sysctl }}"
#   tags: common

- name: yum install yum-utils
  yum:
    name: "yum-utils"
    state: "present"
  changed_when: false
  ignore_errors: true
  tags: common

# - name: yum-config-manager --enable
#   command: yum-config-manager --{{ item.state }} {{ item.name }}
#   loop: "{{ _repo_state_manager }}"
#   changed_when: false
#   ignore_errors: true
#   tags: common

# - name: yum install yum-plugin-fastestmirror
#   yum:
#     name: "yum-plugin-fastestmirror"
#     state: "present"
#   changed_when: false
#   ignore_errors: true
#   tags: common

# - name: Disable yum-plugin-fastestmirror
#   lineinfile:
#     path: "/etc/yum/pluginconf.d/fastestmirror.conf"
#     regexp: "^enabled="
#     line: "enabled=0"
#     state: "present"
#   changed_when: false
#   ignore_errors: true
#   tags: common

# - name: Add signing keys
#   rpm_key:
#     key: "{{ item.gpg }}"
#     state: present
#   loop: "{{ _key }}"
#   register: result
#   until: result is succeeded
#   tags: common

# - name: Add repositories
#   yum_repository:
#     name: "{{ item.name }}"
#     description: "{{ item.name }}"
#     baseurl: "{{ item.repo }}"
#     # gpgkey: http://server.com/keys/somerepo.pub
#     gpgcheck: no
#     repo_gpgcheck: no
#     # params: "{{ my_role_somerepo_params }}"
#     state: present
#     enabled: yes
#   loop: "{{ _repo }}"
#   changed_when: false
#   ignore_errors: true
#   tags: common

- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  changed_when: false
  ignore_errors: true
  tags: common

- name: Install packages
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
    disable_gpg_check: yes
  loop: "{{ _package }}"
  register: result
  until: result is succeeded
  tags: common

# - name: just force systemd to reread configs
#   systemd:
#     daemon_reload: yes
#   tags: common

# - name: Start and enable services
#   systemd:
#     name: "{{ item.name }}"
#     state: started
#     enabled: yes
#     daemon_reload: yes
#   loop: "{{ _service }}"
#   register: result
#   until: result is succeeded
#   tags: common

# - name: Add /usr/local/bin to sudo secure_path
#   lineinfile:
#     line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
#     regexp: "Defaults(\s)*secure_path(\s)*="
#     state: present
#     insertafter: EOF
#     path: /etc/sudoers
#     validate: 'visudo -cf %s'
#   tags: common

# - name: Download script
#   get_url:
#     url: "{{ item.url }}"
#     # checksum: "{{ item.checksum }}"
#     dest: "{{ item.dest }}"
#     owner: root
#     group: root
#     mode: 0755
#   loop: "{{ _install_script }}"
#   register: result
#   until: result is succeeded
#   tags: common

# - name: Execute script
#   shell: "{{ item.dest }}"
#   become: true
#   loop: "{{ _install_script }}"
#   register: result
#   until: result is succeeded
#   tags: common

# - name: Remove script
#   file:
#     path={{ _install_script.dest }}
#     state: absent
#   tags: common
